### ISSUE TITLE
Send a confirmation on registration

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices-2014-2015#24]
Please send a confirmation email to the group when they register. Why not use [Mandrill](https://addons.heroku.com/mandrill)!?

**Comment by Hoverbear** [comment]
@DellaPreston Do you have text you'd like in the email specifically?

**Comment by Hoverbear** [comment]
This is not complete. It's sending emails every time you modify a group. :(

**Comment by Hoverbear** [comment]
153b9d6527f2b2146c56114159c1453870478ee3 contributed to this.

**Comment by Hoverbear** [comment]
@DellaPreston Can you please confirm that this is appropriate?

**Comment by Hoverbear** [comment]
Confirmed!
