### ISSUE TITLE
Add member button is buggy

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices-2014-2015#27]
on the member page, when I go to add a member, I click, the blank form shows, I go to click in Name box, but as my curse-er is on the way, the form collapses. 

this issue seems to repeat several times, and then the form stays, I am puzzled

**Comment by Hoverbear** [comment]
You're right. I think I know the issue. It didn't present itself when hosted locally because my machine was responding to fast, but when it's hosted online there is a delay before it fetches the form.

**Comment by Hoverbear** [comment]
Seems to have been fixed. Please reopen this issue if you're still experiencing it.
