### ISSUE TITLE
Statistics and Graphs

### ISSUE THREAD

**Issue by Hoverbear** [BCAAFC/Gathering-Our-Voices-2014-2015#35]
@DellaPreston Lets get some specifics. :)

We'll use https://developers.google.com/chart/ to create the charts.

**Comment by DellaPreston** [comment]
Please provide statistics and analytics on the following:

### Attendee Statistics
- [ ] Table with totals. For example:

| Type | Total |
| --- | --- |
| Youth | 15 |
| Young Adult | 15 |
| ... | ... |
| Summed Youth | 45 |
| **Total** | 155 |

### Age and Gender
- [ ]  Statistics Table. For example:

| Age | Male | Female | Total |
| --- | --- | --- | --- |
| 14 | 15 | 25 | 40 |
| 15 | 15 | 25 | 40 |
| ... | ... | ... | ... |
| 24 | 15 | 25 | 40 |
| 24+ | 15 | 25 | 40 |
| **Total** | 155 | 255 | 455 |
- [ ] Bar chart breaking down by year the male/female statistics.

### Regional Statistics

Regions are: North, Interior, Fraser, Vancouver Coastal, Vancouver Island, Out of Province
- [ ] Statistics Table. For example: 

| Region | Attendees |
| --- | --- |
| Vancouver Coastal | 15 |
| Fraser | 15 |
| ... | 15 |
| **Total** | 155 |
- [ ] Pie chart breaking down the split.

**Comment by DellaPreston** [comment]
Type of group - drop down
- Friendship Centre
- Off-reserve
- On-reserve
- Other

**Comment by Hoverbear** [comment]
Hi @DellaPreston ,
We didn't collect the type of group. Lets talk tomorrow about it. Please see your revised comment above.
